services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dummy-json-app-dev
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - BASEURL_DUMMYJSON=https://dummyjson.com/products
      - PATH_API=dev/api/v1/products
    command: ["java", "-jar", "/app/app.jar"]
